-- MySQL Script generated by MySQL Workbench
-- mar 21 oct 2025 12:39:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema transporte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema transporte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `transporte` DEFAULT CHARACTER SET utf8 ;
USE `transporte` ;

-- -----------------------------------------------------
-- Table `transporte`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`vendedores` (
  `id_vendedor` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `tipo_identificacion` ENUM('C.C.', 'T.I.', 'C.E.', 'Pasp.') NOT NULL,
  `numero_identificacion` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `celular` VARCHAR(20) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `direccion` VARCHAR(50) NULL,
  `clave` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_vendedor`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transporte`.`agencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`agencias` (
  `id_agencia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `codigo_interno` VARCHAR(2) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`id_agencia`),
  UNIQUE INDEX `codigo_interno_UNIQUE` (`codigo_interno` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transporte`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nit` VARCHAR(45) NOT NULL,
  `razon_social` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transporte`.`localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`localidades` (
  `id_localidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_localidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transporte`.`rutas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`rutas` (
  `id_ruta` INT NOT NULL AUTO_INCREMENT,
  `inicio_ruta` INT NOT NULL,
  `fin_ruta` INT NOT NULL,
  `estado` TINYINT UNSIGNED NOT NULL,
  `costo` DECIMAL UNSIGNED NOT NULL,
  PRIMARY KEY (`id_ruta`, `inicio_ruta`, `fin_ruta`),
  INDEX `inicio_ruta_idx` (`inicio_ruta` ASC) VISIBLE,
  INDEX `fin_ruta_idx` (`fin_ruta` ASC) VISIBLE,
  CONSTRAINT `inicio_ruta`
    FOREIGN KEY (`inicio_ruta`)
    REFERENCES `transporte`.`localidades` (`id_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fin_ruta`
    FOREIGN KEY (`fin_ruta`)
    REFERENCES `transporte`.`localidades` (`id_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transporte`.`conductores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`conductores` (
  `id_conductor` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `tipo_identificacion` ENUM('C.C.', 'T.I.', 'C.E.', 'Pasp.') NOT NULL,
  `numero_identificacion` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(50) NULL,
  `celular` VARCHAR(20) NOT NULL,
  `fecha_nacimiento` DATE NULL,
  `direccion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_conductor`),
  UNIQUE INDEX `numero_identificacion_UNIQUE` (`numero_identificacion` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transporte`.`propietarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`propietarios` (
  `id_propietario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `tipo_identificacion` ENUM('C.C.', 'T.I.', 'C.E.', 'Pasp.') NOT NULL,
  `numero_identificacion` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(50) NULL,
  `celular` VARCHAR(20) NOT NULL,
  `fecha_nacimiento` DATE NULL,
  `direccion` VARCHAR(50) NULL,
  PRIMARY KEY (`id_propietario`),
  UNIQUE INDEX `numero_identificacion_UNIQUE` (`numero_identificacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transporte`.`vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`vehiculos` (
  `id_vehiculo` INT NOT NULL AUTO_INCREMENT,
  `id_propietario` INT NOT NULL,
  `placa` VARCHAR(6) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `anio_fabricacion` YEAR NOT NULL,
  `codigo_interno` VARCHAR(4) NOT NULL,
  `cantidad_puestos` TINYINT NOT NULL,
  PRIMARY KEY (`id_vehiculo`),
  INDEX `id_propietario_idx` (`id_propietario` ASC) VISIBLE,
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC) VISIBLE,
  CONSTRAINT `id_propietario`
    FOREIGN KEY (`id_propietario`)
    REFERENCES `transporte`.`propietarios` (`id_propietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transporte`.`planillas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`planillas` (
  `id_planilla` INT NOT NULL AUTO_INCREMENT,
  `id_ruta` INT NOT NULL,
  `id_conductor` INT NOT NULL,
  `id_vendedor` INT NOT NULL,
  `id_vehiculo` INT NOT NULL,
  `id_agencia` INT NOT NULL,
  `viaje_completado` TINYINT UNSIGNED NOT NULL,
  `hora_salida` TIMESTAMP NULL,
  PRIMARY KEY (`id_planilla`),
  INDEX `id_ruta_idx` (`id_ruta` ASC) VISIBLE,
  INDEX `id_vendedor_idx` (`id_vendedor` ASC) VISIBLE,
  INDEX `id_conductor_idx` (`id_conductor` ASC) VISIBLE,
  INDEX `id_vehiculo_idx` (`id_vehiculo` ASC) VISIBLE,
  INDEX `id_agencia_idx` (`id_agencia` ASC) VISIBLE,
  CONSTRAINT `id_ruta`
    FOREIGN KEY (`id_ruta`)
    REFERENCES `transporte`.`rutas` (`id_ruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_vendedor`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `transporte`.`vendedores` (`id_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_conductor`
    FOREIGN KEY (`id_conductor`)
    REFERENCES `transporte`.`conductores` (`id_conductor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_vehiculo`
    FOREIGN KEY (`id_vehiculo`)
    REFERENCES `transporte`.`vehiculos` (`id_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_agencia`
    FOREIGN KEY (`id_agencia`)
    REFERENCES `transporte`.`agencias` (`id_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transporte`.`tiquetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`tiquetes` (
  `id_tiquete` INT NOT NULL AUTO_INCREMENT,
  `id_planilla` INT NOT NULL,
  PRIMARY KEY (`id_tiquete`, `id_planilla`),
  INDEX `id_planilla_idx` (`id_planilla` ASC) VISIBLE,
  CONSTRAINT `id_planilla`
    FOREIGN KEY (`id_planilla`)
    REFERENCES `transporte`.`planillas` (`id_planilla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transporte`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transporte`.`administradores` (
  `id_vendedor` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `tipo_identificacion` ENUM('C.C.', 'T.I.', 'C.E.', 'Pasp.') NOT NULL,
  `numero_identificacion` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `celular` VARCHAR(20) NULL,
  `fecha_nacimiento` DATE NULL,
  `direccion` VARCHAR(50) NULL,
  `clave` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_vendedor`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
